/*
 * This file was generated by the Gradle "init" task.
 */
//buildscript {
//    ext.kotlin_version = "1.3.70"
//    repositories {
//        mavenCentral()
//    }
//    dependencies {
//        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
//    }
//}
plugins {
//    id "io.spring.dependency-management" version "1.0.8.RELEASE"
//    id "java"
    val kotlinVersion = "1.3.70"
    val springBootVersion = "2.2.4.RELEASE"
//    spring 2.2.4?

//    val springBootVersion = "2.1.4.RELEASE"
    val springBootDependencyManagementVersion = "1.0.9.RELEASE"
    kotlin("jvm") version kotlinVersion apply false
    kotlin("plugin.spring") version kotlinVersion apply false
    kotlin("plugin.jpa") version kotlinVersion apply false
    id("org.springframework.boot") version springBootVersion apply false
    id("io.spring.dependency-management") version springBootDependencyManagementVersion apply false
}


allprojects {
    group = "com.ben"
    version = "0.0.1-SNAPSHOT"
}

subprojects {
//    apply plugin: "kotlin"
//    apply plugin: "maven-publish"
//    apply plugin: "io.spring.dependency-management"



//    dependencyManagement {
//        imports {
//            mavenBom("org.springframework.boot:spring-boot-dependencies:2.1.6.RELEASE")
//        }
//    }

//    sourceCompatibility = "11"
//
//    publishing {
//        publications {
//            maven(MavenPublication) {
//                from(components.java)
//            }
//        }
//    }

//    tasks.withType(JavaCompile) {
//        options.encoding = "UTF-8"
//    }
//    compileKotlin {
//        kotlinOptions {
//            jvmTarget = "11"
//        }
//    }
//    compileTestKotlin {
//        kotlinOptions {
//            jvmTarget = "11"
//        }
//    }
}

//dependencies {
//    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin_version")
//}

